#define EXPERIMENT_CONFIG_START_TIME   0
#define EXPERIMENT_CONFIG_STOP_TIME    1000

#define EXPERIMENT_CONFIG_INPUT_BUFFER_SIZE_BYTES 2000000000
#define EXPERIMENT_CONFIG_OUTPUT_BUFFER_SIZE_BYTES 200000000

#define EXPERIMENT_CONFIG_BUFFER_SIZE_BYTES 200000

//#define NUMBER_OF_TERMINALS 
// Sender data rate
#define EXPERIMENT_CONFIG_SENDER_ONTIME_CONSTANT 2
//#define EXPERIMENT_CONFIG_SENDER_DOWNTIME_MEAN
#define EXPERIMENT_CONFIG_SENDER_DOWNTIME_BOUND 2

#define EXPERIMENT_CONFIG_SENDER_PACKET_SIZE 1040
//#define EXPERIMENT_CONFIG_SENDER_PACKETS_PER_SHORT_FLOW

// sender link, data rate is bps; delay is in mili seconds;
//#define EXPERIMENT_CONFIG_SENDER_LINK_DATA_RATE 133000000
#define EXPERIMENT_CONFIG_SENDER_LINK_DELAY 2

// server link
//#define EXPERIMENT_CONFIG_SERVER_LINK_DATA_RATE 
#define EXPERIMENT_CONFIG_SERVER_LINK_DELAY 2

#define NUMBER_OF_TERMINALS 2
#define EXPERIMENT_CONFIG_SERVER_LINK_DATA_RATE 1000000000000
#define EXPERIMENT_CONFIG_SENDER_DOWNTIME_MEAN 0.1
#define EXPERIMENT_CONFIG_SENDER_PACKETS_PER_SHORT_FLOW 20
#define EXPERIMENT_CONFIG_SENDER_DATA_RATE 160000
