#define EXPERIMENT_CONFIG_BUFFER_SIZE_PACKETS 20
#define EXPERIMENT_CONFIG_BUFFER_SIZE_BYTES 200000
#define EXPERIMENT_CONFIG_START_TIME   2 
#define EXPERIMENT_CONFIG_STOP_TIME    20

#define NUMBER_OF_TERMINALS 200;
// Sender data rate
#define EXPERIMENT_SENDER_ONTIME_CONSTANT 2
#define EXPERIMENT_SENDER_DOWNTIME_MEAN 0.01
#define EXPERIMENT_SENDER_DOWNTIME_BOUND 2

#define EXPERIMENT_SENDER_PACKET_SIZE 1040
#define EXPERIMENT_SENDER_PACKETS_PER_SHORT_FLOW 20000

// sender link, data rate is bps; delay is in mili seconds;
#define EXPERIMENT_CONFIG_SENDER_LINK_DATA_RATE 22200000
#define EXPERIMENT_CONFIG_SENDER_LINK_DELAY 5

// server link
#define EXPERIMENT_CONFIG_SERVER_LINK_DATA_RATE 20000000
#define EXPERIMENT_CONFIG_SERVER_LINK_DELAY 2

